### ISSUE TITLE
File lock while accessing a table in a source

### ISSUE THREAD

**Issue by MarcusKlik** [krlmlr/fstplyr#7]
Hi @krlmlr, I noticed that in the `feather` class object, you opted to [keep a lock](https://github.com/wesm/feather/blob/master/R/R/class.R#L9-L18) on the `feather` file until the user explicitly closes it. That makes sure that the file isn't changed by another process while the user is working with it. On the other hand, in interactive use, it's very easy to re-run a piece of code and loose the reference to the lock:

``` r
library(feather)

# sample file
write_feather(data.frame(X = 1:10), "1.fea")

# get lock
x <- feather("1.fea")

# forget first lock
x <- feather("1.fea")

# write file again
write_feather(data.frame(X = 1:10), "1.fea")
#> Error in writeFeather(x, path): IO error: Failed to open file: 1.fea
```

the file lock takes an effort to remove. For the similar `fst_table` object, I was thinking to keep an exclusive lock on the file only during read- or write operations, but not continuously. That means that in interactive use, the underlying table could have changed. We can detect that with some hash value in the metadata, but still, the existing meta-data in the `tibble` would become invalid.

Do you think the clean way to handle that situation would be a warning or error message in the `fstplyr` client?

thanks!

**Comment by krlmlr** [comment]
Thanks. For now, my primary use case are read-only operations.

The `tbl_fst` (or `tbl` objects in general) don't maintain state: metadata is read once and then cached. I think locking only during file operations is fine, and it's also fine to throw an error if the metadata becomes invalid.

Would it be faster if fstplyr cached the `fst_table` object and not the metadata?

**Comment by MarcusKlik** [comment]
Thanks, nice, then I can provide a hash value in the metadata that can be used to check the validity.

For now, it's probably best to use the metadata because the `fst` version < 0.8.0 is still supported and some small processing [is required to map](https://github.com/fstpackage/fst/blob/develop/src/flex_store.cpp#L126-L134) the new metadata format to the earlier format. I guess the logic for that processing is best kept inside the `fst` package But we could switch when the earlier format is not supported anymore (a few versions and more pressing warnings from now :-)).

Thanks for the pointers!

**Comment by krlmlr** [comment]
Are you suggesting to *not* use the metadata?

**Comment by MarcusKlik** [comment]
Hi @krlmlr, apologies, my remarks were not very clear!

The `fst_table` object is now [available](https://github.com/fstpackage/fst/blob/develop/R/fst_table.R) in the dev version of `fst` and will be on CRAN in a couple of days. It provides a default `data.frame` interface and can be used to implement the `slice()` and `select()` for example.

For slicing, the current logic is identical to your logic in `fstplyr` ([here](https://github.com/krlmlr/fstplyr/blob/master/R/tbl.R#L50-L53)), but faster logic for slicing can now be implemented in `fst` without `fstplyr` having to change it's interface, so it would be nice to use the `fst_table` object in `fstplyr`.

For running delayed operations with higher speed, the `fst_table` object needs a more advanced interface. It needs to accept:

* a row vector (implemented)
* column vectors (implemented)
* row ordering vector (not implemented)
* a map of group ID's (not implemented)
* function to apply (not implemented)

given these parameters, `fst` could selectively load rows and columns in a specific order, collect data in groups and apply a function to those groups. Being able to supply a function to the `fst` API will speed things up because `fst` can perform calculations on the master `R` thread while loading data in the background. If we can supply these and ask `fst` to provide (only) the first few rows of the result, `fstplyr` would be very responsive in interactive mode, printing only a small subset of the data if required.

thanks
