### ISSUE TITLE
Cannot connvert to data.frame

### ISSUE THREAD

**Issue by jllipatz** [krlmlr/fstplyr#8]
Hello,
I was trying to use directly (without loading it) a fst for statistics. What is the way to convert it to as data frame? 
base <- src_fst("V:/PALETTES/ESANE/misc/")
> base
src:  fst files in V:\PALETTES\ESANE\misc\
tbls: CdBA_millions_arrondis, CdBP_millions_arrondis, CdR_millions_arrondis
> a <- tbl(base,"CdBA_millions_arrondis")
> a
# A tibble: 25 x 6
   `01Industrie` `02Construction` `03Commerce` `04Transports_et_entreposage`
           <dbl>            <dbl>        <dbl>                         <dbl>
 1      254760.0         494099.0     717265.0                      106298.0
 2        2958.7           1292.4       2621.8                        1133.0
 3         138.0             67.6         85.9                          32.0
 4            NA          10629.7     101658.9                       20797.0
 5            NA          60949.8     186402.6                      347278.7
 6       13564.6           2335.1       7660.6                       19809.8
 7      136189.9          13120.9      59276.9                      134220.7
 8      567562.4          25099.9      49200.9                       63712.8
 9       63393.2          17757.0      66193.9                       93480.9
10       35349.4           1504.4       3665.6                       35289.3
# ... with 15 more rows, and 2 more variables: `05Services_principalement_marchands` <dbl>,
#   `06Enseignement,_santé_humaine_et_action_sociale` <dbl>
> b <- as.data.frame(a)
Error in as.data.frame.default(a) : 
  impossible de convertir automatiquement la classe  "c("tbl_fst", "tbl")" en un tableau de données (data.frame)

**Comment by krlmlr** [comment]
Thanks, fixed now.
